/**
 * Pure Node.js PDF generator for invoices — no external dependencies.
 * Produces a minimal but valid PDF/1.4 binary in-memory and returns a Buffer.
 */

function escPdfStr(str) {
  return String(str || '').replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function fmt(amount, currency) {
  const num = parseFloat(amount) || 0;
  return `${currency || 'INR'} ${num.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
}

function fmtDate(d) {
  if (!d) return 'N/A';
  try { return new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }); }
  catch { return String(d); }
}

/**
 * @param {Object} invoice
 * @returns {Buffer}
 */
function generateInvoicePdf(invoice) {
  const inv = invoice || {};
  const invoiceNumber = inv.invoiceNumber || inv.invoice_number || 'N/A';
  const tenantName = inv.tenantName || inv.tenant || inv.customer_name || 'N/A';
  const amount = fmt(inv.amount || inv.total, inv.currency);
  const status = String(inv.status || 'N/A').toUpperCase();
  const issuedDate = fmtDate(inv.issuedDate || inv.created_at);
  const dueDate = fmtDate(inv.dueDate || inv.due_date);

  // ── PDF content stream ──────────────────────────────────────────────────────
  const lines = [
    'BT',
    '/F1 26 Tf',
    '50 780 Td',
    `(INVOICE) Tj`,
    'ET',
    // Divider
    '0.85 0.85 0.85 RG',
    '1 w',
    '50 768 m 545 768 l S',
    // Reset colour
    '0 0 0 RG',
    // Invoice meta block
    'BT',
    '/F1 11 Tf',
    '50 750 Td',
    `(Invoice Number:) Tj`,
    '/F2 11 Tf',
    '155 750 Td',
    `(${escPdfStr(invoiceNumber)}) Tj`,
    '/F1 11 Tf',
    '50 733 Td',
    `(Status:) Tj`,
    '/F2 11 Tf',
    '155 733 Td',
    `(${escPdfStr(status)}) Tj`,
    '/F1 11 Tf',
    '50 716 Td',
    `(Issued Date:) Tj`,
    '/F2 11 Tf',
    '155 716 Td',
    `(${escPdfStr(issuedDate)}) Tj`,
    '/F1 11 Tf',
    '50 699 Td',
    `(Due Date:) Tj`,
    '/F2 11 Tf',
    '155 699 Td',
    `(${escPdfStr(dueDate)}) Tj`,
    'ET',
    // Bill To section
    '0.85 0.85 0.85 RG',
    '50 685 m 545 685 l S',
    '0 0 0 RG',
    'BT',
    '/F2 12 Tf',
    '50 668 Td',
    `(BILL TO) Tj`,
    '/F1 11 Tf',
    '50 650 Td',
    `(${escPdfStr(tenantName)}) Tj`,
    'ET',
    // Table header
    '0.95 0.95 0.95 rg',
    '50 610 495 24 re f',
    '0 0 0 rg',
    'BT',
    '/F2 10 Tf',
    '58 619 Td',
    `(DESCRIPTION) Tj`,
    '400 619 Td',
    `(AMOUNT) Tj`,
    'ET',
    // Table row
    '0.95 0.97 1 rg',
    '50 585 495 24 re f',
    '0 0 0 rg',
    'BT',
    '/F1 10 Tf',
    '58 595 Td',
    `(Software Subscription Services) Tj`,
    '400 595 Td',
    `(${escPdfStr(amount)}) Tj`,
    'ET',
    // Divider
    '0.85 0.85 0.85 RG',
    '50 583 m 545 583 l S',
    '0 0 0 RG',
    // Total line
    'BT',
    '/F2 12 Tf',
    '350 560 Td',
    `(TOTAL:) Tj`,
    '/F2 12 Tf',
    '400 560 Td',
    `(${escPdfStr(amount)}) Tj`,
    'ET',
    // Footer
    '0.55 0.55 0.55 rg',
    'BT',
    '/F1 9 Tf',
    '50 60 Td',
    `(Thank you for your business! This invoice was generated by HubNest CRM.) Tj`,
    'ET',
    '0 0 0 rg',
  ];

  const contentStream = lines.join('\n');
  const streamBytes = Buffer.from(contentStream, 'latin1');

  // ── PDF object table ────────────────────────────────────────────────────────
  const objects = [];
  const offsets = [];

  function addObj(content) {
    const idx = objects.length + 1;
    objects.push({ idx, content });
    return idx;
  }

  // obj 1 — Catalog
  const catalogIdx = addObj(`<< /Type /Catalog /Pages 2 0 R >>`);
  // obj 2 — Pages
  const pagesIdx = addObj(`<< /Type /Pages /Kids [3 0 R] /Count 1 >>`);
  // obj 3 — Page
  const pageIdx = addObj(
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 841] ` +
    `/Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>`
  );
  // obj 4 — Content stream
  const streamIdx = addObj(
    `<< /Length ${streamBytes.length} >>\nstream\n${contentStream}\nendstream`
  );
  // obj 5 — Font Helvetica (F1)
  addObj(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`);
  // obj 6 — Font Helvetica-Bold (F2)
  addObj(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>`);

  // ── Build PDF binary ────────────────────────────────────────────────────────
  const parts = [];
  parts.push(Buffer.from('%PDF-1.4\n', 'latin1'));

  for (const obj of objects) {
    offsets.push(parts.reduce((sum, b) => sum + b.length, 0));
    parts.push(Buffer.from(`${obj.idx} 0 obj\n${obj.content}\nendobj\n`, 'latin1'));
  }

  const xrefOffset = parts.reduce((sum, b) => sum + b.length, 0);
  const xrefLines = [`xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`];
  for (const off of offsets) {
    xrefLines.push(String(off).padStart(10, '0') + ' 00000 n \n');
  }

  parts.push(Buffer.from(xrefLines.join(''), 'latin1'));
  parts.push(
    Buffer.from(
      `trailer\n<< /Size ${objects.length + 1} /Root ${catalogIdx} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`,
      'latin1'
    )
  );

  return Buffer.concat(parts);
}

module.exports = { generateInvoicePdf };
